#define _GNU_SOURCE
#include "mem_git.h"
#include "subprocess.h"
#include "nash_limits.h"
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>

/* ── git version control for memory store ──────────────────────── */

int memory_git_run(memory_t *m, const char *const argv[]) {
    return subprocess_run_silent((char *const *)argv, m->dir, 30);
}

void memory_git_init(memory_t *m) {
    if (!m) return;
    char git_path[NASH_PATH_MAX];
    snprintf(git_path, sizeof(git_path), "%s/.git", m->dir);
    struct stat st;
    if (stat(git_path, &st) == 0) return;  /* already initialized */

    const char *init_argv[] = {"git", "init", "-q", NULL};
    if (memory_git_run(m, init_argv) != 0) return;

    /* Configure user for commits (required by git) */
    const char *name_argv[] = {"git", "config", "user.name", "nash", NULL};
    memory_git_run(m, name_argv);
    const char *email_argv[] = {"git", "config", "user.email", "nash@localhost", NULL};
    memory_git_run(m, email_argv);

    /* FIX Flaw G: Create .gitignore to exclude binary embedding files.
     * Embedding vectors (*.emb) are large, frequently regenerated, and
     * not useful in git history — they inflate the repo needlessly. */
    char gitignore_path[NASH_PATH_MAX];
    snprintf(gitignore_path, sizeof(gitignore_path), "%s/.gitignore", m->dir);
    FILE *gi = fopen(gitignore_path, "w");
    if (gi) {
        fprintf(gi, "# Auto-generated by nash — exclude binary embedding files\n"
                     "*.emb\n");
        fclose(gi);
    }

    /* Initial commit with any existing files */
    const char *add_argv[] = {"git", "add", "-A", NULL};
    memory_git_run(m, add_argv);
    const char *commit_argv[] = {"git", "commit", "-q", "--allow-empty",
                                  "-m", "memory: initialize memory store", NULL};
    memory_git_run(m, commit_argv);
}

void memory_git_commit(memory_t *m, const char *msg) {
    if (!m || !msg) return;
    /* FIX #13: Check deferred mode under lock — git_deferred/git_deferred_count
     * are also written by memory_git_defer()/memory_git_flush() on other threads.
     * Without the lock this was a data race (read-modify-write on git_deferred_count). */
    pthread_mutex_lock(&m->mtx);
    if (m->git_deferred) {
        m->git_deferred_count++;
        pthread_mutex_unlock(&m->mtx);
        return;
    }
    pthread_mutex_unlock(&m->mtx);
    char git_path[NASH_PATH_MAX];
    snprintf(git_path, sizeof(git_path), "%s/.git", m->dir);
    struct stat st;
    if (stat(git_path, &st) != 0) return;  /* no git repo */

    const char *add_argv[] = {"git", "add", "-A", NULL};
    memory_git_run(m, add_argv);

    /* Append model signoff if available (like /dream's Consolidated-by:) */
    char full_msg[1024];
    if (m->model) {
        snprintf(full_msg, sizeof(full_msg), "%s\n\nStored-by: %s", msg, m->model);
    } else {
        snprintf(full_msg, sizeof(full_msg), "%s", msg);
    }

    const char *commit_argv[] = {"git", "commit", "-q", "--allow-empty-message",
                                  "-m", full_msg, NULL};
    memory_git_run(m, commit_argv);
}
