#include "tools_internal.h"
#include "scratchpad.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ── scratchpad section operations (GDN-2 inspired) ─── */

/* ── notes (section-based scratchpad) ────────────────── */

static void scratchpad_persist(tool_ctx_t *ctx) {
    scratchpad_save(&ctx->scratch, ctx->session_dir);
}

tool_result_t tool_notes(tool_ctx_t *ctx, cJSON *params) {
    cJSON *content_j = cJSON_GetObjectItem(params, "content");

    /* ── Legacy mode: notes(content="...") ── */
    /* If only 'content' is provided (no 'op'), treat as legacy full-replacement.
     * This maintains backward compatibility with existing prompts/models. */
    cJSON *op_j = cJSON_GetObjectItem(params, "op");
    if (!op_j && content_j && content_j->valuestring) {
        /* Parse content for section headers (## name) and split into sections */
        const char *text = content_j->valuestring;
        const char *p = text;
        int found_sections = 0;

        /* Quick scan: does the content contain "## " section headers?
         * FIX B7: Only parse sections if the text STARTS with "## " — this
         * means it was generated by scratchpad_serialize(). Content that
         * merely contains "\n## " in the body (e.g., markdown with nested
         * headers) should not be split into sections. */
        if (strncmp(text, "## ", 3) == 0) {
            /* Parse structured content into sections */
            scratchpad_free(&ctx->scratch);

            while (p && *p) {
                if (strncmp(p, "## ", 3) == 0 || (p > text && strncmp(p, "\n## ", 4) == 0)) {
                    if (*p == '\n') p++;
                    const char *hdr = p + 3;
                    const char *hdr_end = strchr(hdr, '\n');
                    if (!hdr_end) hdr_end = hdr + strlen(hdr);

                    char sec_name[256];
                    size_t nlen = (size_t)(hdr_end - hdr);
                    if (nlen >= sizeof(sec_name)) nlen = sizeof(sec_name) - 1;
                    memcpy(sec_name, hdr, nlen);
                    sec_name[nlen] = '\0';

                    const char *body = (*hdr_end) ? hdr_end + 1 : hdr_end;
                    /* Find end of section (next ## or end) */
                    const char *body_end = strstr(body, "\n## ");
                    if (!body_end) body_end = body + strlen(body);

                    /* Trim trailing whitespace */
                    while (body_end > body && (*(body_end-1) == '\n' || *(body_end-1) == ' '))
                        body_end--;

                    size_t blen = (size_t)(body_end - body);
                    char *sec_content = malloc(blen + 1);
                    if (sec_content) {
                        memcpy(sec_content, body, blen);
                        sec_content[blen] = '\0';
                        scratchpad_write(&ctx->scratch, sec_name, sec_content, 5);
                        free(sec_content);
                        found_sections++;
                    }

                    p = (body_end < body + strlen(body)) ? strstr(body, "\n## ") : NULL;
                    if (!p) break;
                } else {
                    p = strstr(p, "\n## ");
                }
            }
        }

        if (!found_sections) {
            /* No section headers — store as single "default" section */
            scratchpad_free(&ctx->scratch);
            scratchpad_write(&ctx->scratch, "default", text, 5);
        }

        scratchpad_persist(ctx);

        char *full = scratchpad_serialize(&ctx->scratch);
        char *hash = store_save(ctx->store, full ? full : "");
        char *alias = tool_register_alias(ctx, hash ? hash : "");

        cJSON *meta = cJSON_CreateObject();
        cJSON_AddStringToObject(meta, "status", "ok");
        cJSON_AddNumberToObject(meta, "sections", ctx->scratch.count);
        cJSON_AddStringToObject(meta, "ref", alias);

        tools_inject_thought(ctx, params);
        journal_append(ctx->journal, ctx->react_loop, ctx->step, "notes", params, alias,
                       full ? strlen(full) : 0, 0, NULL, NULL);

        char *ref_copy = strdup(alias);
        free(alias);
        free(hash);
        free(full);
        return tools_make_result(1, meta, ref_copy);
    }

    /* ── Section-based mode: notes(op, section, content, priority) ── */
    if (!op_j || !op_j->valuestring)
        return tools_make_error("missing 'op' parameter (write|append|read|clear|list) or 'content' for legacy mode");

    const char *op = op_j->valuestring;
    cJSON *section_j = cJSON_GetObjectItem(params, "section");
    const char *section = section_j && section_j->valuestring ? section_j->valuestring : NULL;
    const char *content = content_j && content_j->valuestring ? content_j->valuestring : NULL;
    cJSON *priority_j = cJSON_GetObjectItem(params, "priority");
    int priority = priority_j ? (int)cJSON_GetNumberValue(priority_j) : 5;

    if (strcmp(op, "write") == 0) {
        if (!section) return tools_make_error("'write' requires 'section' parameter");
        if (!content) return tools_make_error("'write' requires 'content' parameter");

        int rc = scratchpad_write(&ctx->scratch, section, content, priority);
        if (rc != 0) return tools_make_error("scratchpad full (max 32 sections)");

        scratchpad_persist(ctx);

        cJSON *meta = cJSON_CreateObject();
        cJSON_AddStringToObject(meta, "status", "ok");
        cJSON_AddStringToObject(meta, "op", "write");
        cJSON_AddStringToObject(meta, "section", section);
        cJSON_AddNumberToObject(meta, "sections", ctx->scratch.count);

        /* Store content for full audit trail */
        char *w_hash = store_save(ctx->store, content);
        char *w_alias = tool_register_alias(ctx, w_hash ? w_hash : "");
        tools_inject_thought(ctx, params);
        journal_append(ctx->journal, ctx->react_loop, ctx->step, "notes", params, w_alias,
                       strlen(content), 0, NULL, NULL);
        free(w_alias); free(w_hash);
        return tools_make_result(1, meta, NULL);

    } else if (strcmp(op, "append") == 0) {
        if (!section) return tools_make_error("'append' requires 'section' parameter");
        if (!content) return tools_make_error("'append' requires 'content' parameter");

        int rc = scratchpad_append(&ctx->scratch, section, content, priority);
        if (rc != 0) return tools_make_error("scratchpad full");

        scratchpad_persist(ctx);

        int idx = scratchpad_find(&ctx->scratch, section);
        cJSON *meta = cJSON_CreateObject();
        cJSON_AddStringToObject(meta, "status", "ok");
        cJSON_AddStringToObject(meta, "op", "append");
        cJSON_AddStringToObject(meta, "section", section);
        cJSON_AddNumberToObject(meta, "total_chars",
                                idx >= 0 ? (double)strlen(ctx->scratch.sections[idx].content) : 0);

        /* Store content for full audit trail */
        char *a_hash = store_save(ctx->store, content);
        char *a_alias = tool_register_alias(ctx, a_hash ? a_hash : "");
        tools_inject_thought(ctx, params);
        journal_append(ctx->journal, ctx->react_loop, ctx->step, "notes", params, a_alias,
                       strlen(content), 0, NULL, NULL);
        free(a_alias); free(a_hash);
        return tools_make_result(1, meta, NULL);

    } else if (strcmp(op, "read") == 0) {
        if (!section) return tools_make_error("'read' requires 'section' parameter");

        int idx = scratchpad_find(&ctx->scratch, section);
        if (idx < 0) return tools_make_error("section not found");

        const char *sec_content = ctx->scratch.sections[idx].content;
        char *hash = store_save(ctx->store, sec_content);
        char *alias = tool_register_alias(ctx, hash ? hash : "");

        cJSON *meta = cJSON_CreateObject();
        cJSON_AddStringToObject(meta, "section", section);
        cJSON_AddNumberToObject(meta, "chars", (double)strlen(sec_content));
        cJSON_AddNumberToObject(meta, "priority", ctx->scratch.sections[idx].priority);
        cJSON_AddStringToObject(meta, "ref", alias);

        tools_inject_thought(ctx, params);
        journal_append(ctx->journal, ctx->react_loop, ctx->step, "notes", params, alias,
                       strlen(sec_content), 0, NULL, NULL);

        char *ref_copy = strdup(alias);
        free(alias);
        free(hash);
        return tools_make_result(1, meta, ref_copy);

    } else if (strcmp(op, "clear") == 0) {
        if (!section) return tools_make_error("'clear' requires 'section' parameter");

        int rc = scratchpad_clear(&ctx->scratch, section);
        if (rc != 0) return tools_make_error("section not found");

        scratchpad_persist(ctx);

        cJSON *meta = cJSON_CreateObject();
        cJSON_AddStringToObject(meta, "status", "ok");
        cJSON_AddStringToObject(meta, "op", "clear");
        cJSON_AddStringToObject(meta, "section", section);
        cJSON_AddNumberToObject(meta, "sections", ctx->scratch.count);

        /* Store clear/delete status for audit trail */
        {
            char *c_str = cJSON_Print(meta);
            char *c_hash = store_save(ctx->store, c_str ? c_str : "{}");
            char *c_alias = tool_register_alias(ctx, c_hash ? c_hash : "");
            tools_inject_thought(ctx, params);
            journal_append(ctx->journal, ctx->react_loop, ctx->step, "notes", params, c_alias,
                           0, 0, NULL, NULL);
            free(c_alias); free(c_hash); free(c_str);
        }
        return tools_make_result(1, meta, NULL);

    } else if (strcmp(op, "list") == 0) {
        str_t out = str_new(512);
        for (int i = 0; i < ctx->scratch.count; i++) {
            str_appendf(&out, "  %s (priority:%d, %zu chars)\n",
                        ctx->scratch.sections[i].name,
                        ctx->scratch.sections[i].priority,
                        strlen(ctx->scratch.sections[i].content));
        }

        cJSON *meta = cJSON_CreateObject();
        cJSON_AddStringToObject(meta, "op", "list");
        cJSON_AddNumberToObject(meta, "sections", ctx->scratch.count);
        if (out.len > 0)
            cJSON_AddStringToObject(meta, "listing", out.data);

        /* Store listing for audit trail */
        {
            char *l_hash = store_save(ctx->store, out.len > 0 ? out.data : "{}");
            char *l_alias = tool_register_alias(ctx, l_hash ? l_hash : "");
            tools_inject_thought(ctx, params);
            journal_append(ctx->journal, ctx->react_loop, ctx->step, "notes", params, l_alias,
                           out.len, ctx->scratch.count, NULL, NULL);
            free(l_alias); free(l_hash);
        }

        str_free(&out);
        return tools_make_result(1, meta, NULL);

    } else {
        return tools_make_error("unknown op (use: write, append, read, clear, list)");
    }
}
